### ISSUE TITLE
닉네임 설정뷰 작성

### ISSUE THREAD

**Issue by JEONG-J** [24-2-CapstoneDesign/Front_iOS#1]
## Issue: ✅ Todo
Todo 사항을 입력해주세요

## ✏️ Description
프로필 생성을 위한 뷰 작성

## To-Do List
- [x] 상단 이미지 프로필 추가 버튼 생성하기
- [x] 닉네임 텍스트 필드 만들기
- [x] 추가하기 버튼 생성

### 제약사항
1. 이미지 선택시 한 장으로 제한할 것
2. 제네릭을 통해 앨범 부르도록 구현하기
### 주의사항
iPhone 15 Pro max와 iPhone 10 구현하기
