### ISSUE TITLE
프로필 설정 뷰 및 로그인 뷰 API 구현

### ISSUE THREAD

**Issue by JEONG-J** [24-2-CapstoneDesign/Front_iOS#6]
## Issue: ✅ Todo

Todo 사항을 입력해주세요

## ✏️ Description
설명을 작성합니다

## To-Do List
- [x] 프로필 지정 뷰에서 사진 피커로 불러오도록 최대 1장만 선택 가능
- [x] 로그인 뷰 API 연결 -> 암호화 키로 구현하기
- [x] 모야로 토큰 자동 처리 구현 및 토큰 넘겨주는 데이터 모델 구현
- [x] 프로필 지정 뷰에서 사진과 닉네임 전달하는 API 구현

## ETC
1. 토큰 갱신처리 자동으로 이루어지도록 작성되었는가?
2. 루트뷰 변경이 잘 이루어지도록 했는가?

**Comment by JEONG-J** [comment]
API 설계가 안되어 있으므로, 잠시 보류

**Comment by JEONG-J** [comment]
프로필 텍스트 입력 시 빈 배경 터치할 때 키보드 사라지도록 처리
