### ISSUE TITLE
5월 1주차 처리해야할 것

### ISSUE THREAD

**Issue by JEONG-J** [24-2-CapstoneDesign/Front_iOS#9]
## Issue: ✅ Todo

Todo 사항을 입력해주세요

## ✏️ Description
5월 1주차 완성해야하는 뷰 작성하기

## To-Do List
- [x] 로그인 -> 닉네임 설정 뷰 루트뷰 전환 기능
- [x] 메인 뷰 최상단 Radius 뷰 추가
- [x] 프로필 이미지 + 닉네임 보여지는 뷰 :: 닉네임은 싱글톤 패턴으로 글로벌하게 사용되도록 저장되고, 이를 불러와 보여진다.
- [x] 커스텀 탭바 구현하기
